### ISSUE TITLE
Make header tests pass explicit heading level, fix jquery selector

### ISSUE THREAD

**Issue by kevee** [quailjs/quail#121]
Per [this comment](https://github.com/kevee/quail/commit/4d05c73d409f8493b3708c2dd2a2071b2bb51e2f#commitcomment-5107869) on headers, do a little cleanup:
- Change the `header` component to `headingLevel` to be more explicit.
- Add more test cases for odd heading combinations.
- Remove the `selector` option from tests that use the `heading` component and change to a `headingLevel` option instead, like:

```
headerH4: 
  components: 
    - "headingLevel"
  headingLevel: 4
  tags: 
    - "header"
    - "content"
  testability: 0
  type: "headingLevel"
  guidelines:
    wcag:
      2.4.6:
        techniques:
          - "G130"
...
```
