### ISSUE TITLE
Move code examples to tests.yml, remove docs folder

### ISSUE THREAD

**Issue by kevee** [quailjs/quail#128]
Most test information can be gleaned from the quailjs.org site now, except test examples that are still in .rst files in `/docs`. We could move the two non-test files to the project site. If we added an `examples` directive to tests like so, it would be great for reporting and feedback:

```yaml
imgHasAlt:
  selector : "img:not(img[alt])"
  ...
  examples:
    pass:
      en: "<img src=\"kogepan.jpg\" alt=\"Kogepan in a rain coat.\" />"
    fail:
      en: "<img src=\"kogepan.jpg\"/>"
```
